name: 自动获取ss节点

on:
  workflow_dispatch:  # 使工作流支持手动触发
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当创建 PR 到 main 分支时触发

jobs:
  build:
    runs-on: macos-latest  # 在 macOS 上编译
    steps:
      - name: 获取仓库代码
        uses: actions/checkout@v3  # 获取代码

      - name: 执行文件点击打开获取ss节点信息
        run: |
          ss_output=$(./ss)
          echo "$ss_output"
          echo "$ss_output" > nodes.txt
          echo "SS节点信息已获取并保存到 nodes.txt"

      - name: 设置GIST_TOKEN
        run: echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> $GITHUB_ENV

      - name: 创建或更新Gist
        run: |
          gist_id="01aae4453fff5a78a7c6ed0cfa6b0ac1"  # 替换为你的Gist ID
          if [ -z "$gist_id" ]; then
            curl -X POST -H "Authorization: token $GIST_TOKEN" -d '{"description":"SS 节点信息","public":false,"files":{"nodes.txt":{"content":"'"$(cat nodes.txt)"'"}}}' https://api.github.com/gists
          else
            curl -X PATCH -H "Authorization: token $GIST_TOKEN" -d '{"files":{"nodes.txt":{"content":"'"$(cat nodes.txt)"'"}}}' https://api.github.com/gists/$gist_id
          fi

      - name: 提交并推送 nodes.txt 文件
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add nodes.txt
          git commit -m "Update nodes.txt with latest SS node information"
          git push origin main
